# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies42night', '0003_status_description_from_filmweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='rating_from_filmweb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
