# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies42night', '0004_status_rating_from_filmweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_from_filmweb', models.TextField(max_length=10000, null=True)),
                ('rating_from_filmweb', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='description_from_filmweb',
        ),
        migrations.RemoveField(
            model_name='status',
            name='rating_from_filmweb',
        ),
    ]
