# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies42night', '0005_create_details_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies42night.Movie'),
        ),
    ]
