# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies42night', '0010_auto_20170903_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
